# TCL File Generated by Component Editor 20.1
# Wed Dec 02 10:47:43 JST 2020
# DO NOT MODIFY


# 
# ulong2_to_l8 "ulong2_to_l8" v20.1
#  2020.12.02.10:47:43
# 
# 

# 
# request TCL package from ACDS 20.1
# 
package require -exact qsys 20.1


# 
# module ulong2_to_l8
# 
set_module_property DESCRIPTION ""
set_module_property NAME ulong2_to_l8
set_module_property VERSION 20.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ulong2_to_l8
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ulong2_to_l8
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ulong2_to_l8.v VERILOG PATH ulong2_to_l8.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port clock clk clk Input 1


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clock
set_interface_property out associatedReset rst
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyAllowance 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""
set_interface_property out IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port out out_data data Output 64
add_interface_port out out_startofpacket startofpacket Output 1
add_interface_port out out_empty empty Output 3
add_interface_port out out_valid valid Output 1
add_interface_port out out_ready ready Input 1
add_interface_port out out_endofpacket endofpacket Output 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock ""
set_interface_property rst synchronousEdges NONE
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""
set_interface_property rst IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port rst arst_n reset_n Input 1


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock clock
set_interface_property in associatedReset rst
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits false
set_interface_property in maxChannel 0
set_interface_property in readyAllowance 0
set_interface_property in readyLatency 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""
set_interface_property in IPXACT_REGISTER_MAP_VARIABLES ""

add_interface_port in in_data data Input 128
add_interface_port in in_valid valid Input 1
add_interface_port in in_ready ready Output 1

